### ISSUE TITLE
tcp收到心跳包后，返回encode信息报错。

### ISSUE THREAD

**Issue by JeniTurtle** [cevio/dubbo.ts#3]
这个报错不太明白，求解惑。
------
2020-03-03 17:02:24,565 ERROR 82355 nodejs.TypeError: Cannot read property 'requestId' of undefined
    at Context.setRequestId (/Users/knows/Sites/weds/message-platform/node_modules/dubbo.ts/dist/provider/context.js:100:36)
    at Context.encodeHead (/Users/knows/Sites/weds/message-platform/node_modules/dubbo.ts/dist/provider/context.js:117:14)
    at Context.encode (/Users/knows/Sites/weds/message-platform/node_modules/dubbo.ts/dist/provider/context.js:96:27)
    at Promise.resolve.then.catch.e (/Users/knows/Sites/weds/message-platform/node_modules/dubbo.ts/dist/provider/connection.js:44:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
------
![image](https://user-images.githubusercontent.com/15798752/75758328-dcc67200-5d6e-11ea-9841-741717d72976.png)
这里是监听socket的data事件的回调方法，执行报文decode方法时会判断是不是心跳包，如果是心跳包就发送心跳结果返回回去。
![image](https://user-images.githubusercontent.com/15798752/75758674-637b4f00-5d6f-11ea-858b-2120ee08c2f8.png)
但是下面还会执行this.send()方法，send方法中有用到req这个成员属性，但是这个成员属性是在decode方法中声明的，由于心跳处理直接结束了，没有声明req属性并复制，所以会导致报错。
![image](https://user-images.githubusercontent.com/15798752/75758898-a4736380-5d6f-11ea-8a6b-7b1f3cfa3296.png)

**Comment by cevio** [comment]
@JeniTurtle 我先验证下是不是如您所说的问题。

**Comment by cevio** [comment]
@JeniTurtle 你直接跑肯定不对啊，因为我里面的参数和你的不同。我这边没有问题。你尝试修改下看看？
